package com.company.PhoneJava.entities.service;

public enum BillableServiceType {
  TELEVISION,
  MOBILE_INTERNET,
  HOME_INTERNET,
  WORKPLACE_INTERNET,
  ELECTRONIC_SIGNATURE,
  TRAVEL_INSURANCE,
  DEVICE_INSURANCE,
  SERVICE_ABOARD,
  INTERNATIONAL_CALLS
}
