SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE t_account;
TRUNCATE TABLE t_customer;
TRUNCATE TABLE t_ordered_service;
TRUNCATE TABLE t_phone_number;
TRUNCATE TABLE t_billable_service;
SET REFERENTIAL_INTEGRITY TRUE;